import React, { useEffect, useState } from 'react';
import { ArrowRight, Bot, BriefcaseBusiness, Check, ChevronDown, Code2, Download, ExternalLink, Github, GraduationCap, Linkedin, Mail, MapPin, MessageSquare, Network, ShieldCheck, Sparkles } from 'lucide-react';
import ChatInterface from './components/ChatInterface';
import { API_URL, RESUME_DATA } from './constants';
import { EVIDENCE, EXPERIENCE, ML_LIFECYCLE, PERSONAL_INFO, PROFILE, SELECTED_WORK, SKILLS, type ExperienceEntry, type SelectedWork } from './portfolioData';
import type { Project } from './types';

const NAV_ITEMS = [['Profile', '#profile'], ['Experience', '#experience'], ['Selected Work', '#selected-work'], ['Skills', '#skills'], ['Education', '#education'], ['Academic Work', '/academic-projects'], ['Contact', '#contact']] as const;
const sectionHeading = 'text-2xl font-bold tracking-tight text-white sm:text-3xl';
const card = 'rounded-2xl border border-slate-800 bg-slate-900/65';

function TagList({ items, tone = 'indigo' }: { items: string[]; tone?: 'indigo' | 'emerald' }) {
  const color = tone === 'emerald' ? 'border-emerald-400/15 bg-emerald-400/5 text-emerald-200' : 'border-indigo-400/15 bg-indigo-400/5 text-indigo-200';
  return <ul className="flex flex-wrap gap-2" aria-label="Technologies">{items.map((item) => <li key={item} className={`rounded-md border px-2.5 py-1 text-xs ${color}`}>{item}</li>)}</ul>;
}

function ExperienceCard({ item }: { item: ExperienceEntry }) {
  return <article className={`${card} p-5 sm:p-7 ${item.secondary ? 'opacity-75' : ''}`}>
    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-xl font-semibold text-white">{item.role}</h3><p className="mt-1 font-medium text-indigo-300">{item.company}</p></div><time className="text-sm text-slate-400">{item.period}</time></div>
    <p className="mt-4 leading-7 text-slate-300">{item.summary}</p>
    {item.highlights && <ul className="mt-5 space-y-3">{item.highlights.map((highlight) => <li key={highlight} className="flex gap-3 text-sm leading-6 text-slate-300"><Check className="mt-1 h-4 w-4 shrink-0 text-indigo-400" aria-hidden="true" /><span>{highlight}</span></li>)}</ul>}
    <div className="mt-5"><TagList items={item.technologies} /></div>
  </article>;
}

function WorkCard({ item, featured }: { item: SelectedWork; featured?: boolean }) {
  const content = <><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-semibold text-white">{item.title}</h3>{item.link && <ExternalLink className="h-5 w-5 shrink-0 text-slate-500" aria-hidden="true" />}</div><p className="mt-4 leading-7 text-slate-300">{item.description}</p>
    {(item.capabilities || item.evidence) && <ul className="mt-5 grid gap-2 sm:grid-cols-2">{(item.capabilities || item.evidence || []).map((point) => <li key={point} className="flex gap-2 text-sm text-slate-300"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" aria-hidden="true" />{point}</li>)}</ul>}<div className="mt-6"><TagList items={item.technologies} tone="emerald" /></div></>;
  const classes = `${card} group p-5 transition-colors hover:border-indigo-400/40 sm:p-7 ${featured ? 'lg:col-span-2' : ''}`;
  return item.link ? <a className={classes} href={item.link} target="_blank" rel="noopener noreferrer" aria-label={`${item.title} (opens in a new tab)`}>{content}</a> : <article className={classes}>{content}</article>;
}

function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className="sticky top-0 z-30 border-b border-slate-800/80 bg-slate-950/90 backdrop-blur"><nav className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 lg:px-10" aria-label="Primary navigation">
    <a href="/" className="font-semibold tracking-tight text-white" aria-label="Panagiotis Paltsokas home">Panagiotis <span className="text-indigo-400">Paltsokas</span></a>
    <button className="rounded-lg border border-slate-700 p-2 text-slate-300 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation"><ChevronDown className={`h-5 w-5 transition-transform ${menuOpen ? 'rotate-180' : ''}`} /></button>
    <div className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-full flex-col gap-1 border-b border-slate-800 bg-slate-950 p-4 md:static md:flex md:flex-row md:border-0 md:bg-transparent md:p-0`}>{NAV_ITEMS.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2 text-sm text-slate-400 transition-colors hover:bg-slate-800 hover:text-white">{label}</a>)}</div>
  </nav></header>;
}

function AcademicCard({ project }: { project: Project }) {
  const pdfUrl = project.pdfPath ? `${API_URL}/kb/pdf/${encodeURIComponent(project.pdfPath)}` : undefined;
  return <article className={`${card} flex h-full flex-col p-5`}><h3 className="text-lg font-semibold text-white">{project.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-4"><TagList items={project.technologies.slice(0, 5)} /></div><div className="mt-5 flex flex-wrap gap-3">{pdfUrl && <a href={pdfUrl} download className="inline-flex items-center gap-2 text-sm font-medium text-indigo-300 hover:text-indigo-200"><Download className="h-4 w-4" /> Download PDF</a>}{project.link && <a href={project.link} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-medium text-slate-300 hover:text-white"><Github className="h-4 w-4" /> Repository</a>}</div></article>;
}

function projectCategory(project: Project) {
  const value = `${project.title} ${project.description} ${project.technologies.join(' ')}`.toLowerCase();
  if (value.includes('time series') || value.includes('forecast')) return 'Time-series forecasting';
  if (value.includes('gan') || value.includes('generative') || value.includes('autoencoder')) return 'Generative models';
  if (value.includes('cluster') || value.includes('unsupervised')) return 'Unsupervised learning';
  if (value.includes('neural') || value.includes('mnist')) return 'Neural networks';
  if (value.includes('ensemble') || value.includes('decision tree') || value.includes('random forest')) return 'Ensemble methods';
  if (value.includes('classification') || value.includes('classifier') || value.includes('svm')) return 'Classification';
  if (value.includes('regression')) return 'Regression and statistical learning';
  return 'Exploratory data analysis';
}

function AcademicProjectsPage() {
  const grouped = RESUME_DATA.projects.reduce<Record<string, Project[]>>((groups, project) => { const category = projectCategory(project); groups[category] = [...(groups[category] || []), project]; return groups; }, {});
  return <div className="min-h-screen bg-slate-950 text-slate-100"><Header /><main className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10"><a href="/" className="inline-flex items-center gap-2 text-sm text-indigo-300 hover:text-indigo-200">← Back to portfolio</a><p className="mt-10 text-sm font-semibold uppercase tracking-[0.2em] text-indigo-400">Archive</p><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl">Machine Learning Foundations & Academic Work</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">These projects document the machine learning foundations developed during my MSc and independent study. They are retained as evidence of breadth and technical progression, while my main portfolio focuses on current applied AI/ML engineering work.</p>
    <div className="mt-14 space-y-14">{Object.entries(grouped).map(([category, projects]) => <section key={category}><h2 className="text-2xl font-semibold text-white">{category}</h2><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <AcademicCard key={project.id} project={project} />)}</div></section>)}</div></main></div>;
}

function PortfolioPage() {
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => { const update = () => setIsMobile(window.innerWidth < 768); update(); window.addEventListener('resize', update); return () => window.removeEventListener('resize', update); }, []);
  return <div className="min-h-screen overflow-x-hidden bg-slate-950 text-slate-100"><Header /><main>
    <section className="relative border-b border-slate-800" aria-labelledby="hero-title"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(99,102,241,0.18),transparent_35%)]" /><div className="relative mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[1fr_340px] lg:px-10 lg:py-28"><div className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-indigo-400">{PERSONAL_INFO.title}</p><h1 id="hero-title" className="mt-4 text-4xl font-bold tracking-[-0.04em] text-white sm:text-6xl lg:text-7xl">{PERSONAL_INFO.name}</h1><p className="mt-5 max-w-3xl text-xl font-medium leading-8 text-indigo-200 sm:text-2xl">{PERSONAL_INFO.headline}</p><div className="mt-8 max-w-4xl space-y-4 text-base leading-8 text-slate-300 sm:text-lg">{PERSONAL_INFO.intro.map((text) => <p key={text}>{text}</p>)}</div><div className="mt-9 flex flex-wrap gap-3"><a href={PERSONAL_INFO.resume} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-indigo-500 px-5 py-3 font-semibold text-white transition-colors hover:bg-indigo-400"><Download className="h-4 w-4" /> Download Resume</a><a href={`mailto:${PERSONAL_INFO.email}`} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-5 py-3 font-medium text-slate-200 hover:border-slate-500"><Mail className="h-4 w-4" /> Email me</a></div></div>
      <aside className={`${card} self-end p-6`} aria-label="Contact details"><div className="flex items-center gap-3 text-slate-300"><MapPin className="h-5 w-5 text-indigo-400" /> {PERSONAL_INFO.location}</div><div className="mt-5 flex gap-3"><a href={PERSONAL_INFO.github} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-slate-700 p-3 text-slate-300 hover:text-white" aria-label="GitHub profile"><Github /></a><a href={PERSONAL_INFO.linkedin} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-slate-700 p-3 text-slate-300 hover:text-white" aria-label="LinkedIn profile"><Linkedin /></a></div><p className="mt-6 border-t border-slate-800 pt-5 text-sm leading-6 text-slate-400">End-to-end ML systems for time-series, IoT, federated, browser, and edge environments.</p></aside></div></section>
    <section aria-label="Professional evidence" className="border-b border-slate-800 bg-slate-900/45"><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-px bg-slate-800 px-5 md:grid-cols-5 lg:px-10">{EVIDENCE.map((metric) => <div key={metric.label} className="bg-slate-900 px-4 py-6 text-center"><strong className="block text-2xl text-white">{metric.value}</strong><span className="mt-1 block text-xs leading-5 text-slate-400">{metric.label}</span></div>)}</div></section>
    <div className="mx-auto max-w-[1440px] space-y-24 px-5 py-20 lg:px-10 lg:py-28">
      <section id="profile" className="scroll-mt-24" aria-labelledby="profile-title"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-400">Profile</p><h2 id="profile-title" className={`mt-3 ${sectionHeading}`}>Applied engineering, rigorous validation, clear communication.</h2></div><div className="space-y-5 text-base leading-8 text-slate-300">{PROFILE.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><div className={`${card} mt-10 p-6`}><h3 className="flex items-center gap-2 font-semibold text-white"><Network className="h-5 w-5 text-indigo-400" /> Complete ML lifecycle</h3><ol className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{ML_LIFECYCLE.map((step, index) => <li key={step} className="flex items-center gap-3 rounded-xl bg-slate-950/70 p-3 text-sm text-slate-300"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-indigo-500/15 text-xs font-bold text-indigo-300">{index + 1}</span>{step}</li>)}</ol></div></section>
      <section id="experience" className="scroll-mt-24" aria-labelledby="experience-title"><div className="flex items-center gap-3"><BriefcaseBusiness className="text-indigo-400" /><h2 id="experience-title" className={sectionHeading}>Experience</h2></div><div className="mt-8 grid gap-6">{EXPERIENCE.map((item) => <ExperienceCard key={`${item.company}-${item.role}`} item={item} />)}</div></section>
      <section id="selected-work" className="scroll-mt-24" aria-labelledby="work-title"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-400">Systems & validation</p><h2 id="work-title" className={`mt-3 ${sectionHeading}`}>Selected Work</h2><p className="mt-4 leading-7 text-slate-400">A curated view of applied ML systems, demonstrators, and portfolio products.</p></div><div className="mt-8 grid gap-6 lg:grid-cols-2">{SELECTED_WORK.map((item, index) => <WorkCard key={item.title} item={item} featured={index < 2} />)}</div></section>
      <section id="skills" className="scroll-mt-24" aria-labelledby="skills-title"><div className="flex items-center gap-3"><Code2 className="text-indigo-400" /><h2 id="skills-title" className={sectionHeading}>Technical Capabilities</h2></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{SKILLS.map((group) => <details key={group.name} className={`${card} group p-6`} open={group.name === 'Applied Machine Learning' || group.name === 'ML Systems Engineering'}><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-white">{group.name}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{group.summary}</p></div><ChevronDown className="h-5 w-5 shrink-0 text-slate-500 transition-transform group-open:rotate-180" /></div></summary><div className="mt-5"><TagList items={group.skills} /></div></details>)}</div></section>
      <section id="education" className="scroll-mt-24" aria-labelledby="education-title"><div className="flex items-center gap-3"><GraduationCap className="text-indigo-400" /><h2 id="education-title" className={sectionHeading}>Education</h2></div><div className="mt-8 grid gap-5 md:grid-cols-2">{RESUME_DATA.education.map((item) => <article key={item.id} className={`${card} p-6`}><p className="text-sm text-indigo-300">{item.year}</p><h3 className="mt-2 text-xl font-semibold text-white">{item.degree}</h3><p className="mt-2 text-slate-400">{item.school}</p>{item.grade && <p className="mt-4 text-sm font-medium text-emerald-300">Grade: {item.grade}</p>}</article>)}</div></section>
      <section aria-labelledby="certifications-title"><h2 id="certifications-title" className="text-xl font-semibold text-white">Certifications</h2><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{RESUME_DATA.certifications?.map((cert) => <a key={cert.id} href={cert.credentialUrl} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-slate-800 bg-slate-900/40 p-4 hover:border-slate-600"><h3 className="text-sm font-medium text-slate-200">{cert.title.replace('β€“', '–')}</h3><p className="mt-2 text-xs text-slate-500">{cert.issuer} · {cert.year.replace(/\(In Progress\)/i, '— In progress')}</p></a>)}</div></section>
      <section id="academic-work" className={`${card} scroll-mt-24 p-7 sm:p-10`}><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-400">Archive</p><h2 className="mt-3 text-2xl font-bold text-white">Machine Learning Foundations & Academic Work</h2><p className="mt-3 leading-7 text-slate-400">MSc and independent-study projects remain available as evidence of technical breadth without competing with current applied engineering work.</p></div><a href="/academic-projects" className="inline-flex shrink-0 items-center gap-2 font-semibold text-indigo-300 hover:text-indigo-200">View academic projects <ArrowRight className="h-4 w-4" /></a></div></section>
      <section id="contact" className="scroll-mt-24 rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 p-8 sm:p-12" aria-labelledby="contact-title"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-indigo-100"><Sparkles className="h-5 w-5" /> Virtual Panos</div><h2 id="contact-title" className="mt-3 text-3xl font-bold text-white">Explore the work through conversation.</h2><p className="mt-4 max-w-3xl leading-7 text-indigo-100">Ask Virtual Panos about my work in applied machine learning, municipal parking forecasting, federated learning, edge and browser inference, data pipelines, or my transition from mathematics into AI engineering.</p></div><button onClick={() => setIsChatOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-white px-5 py-3 font-semibold text-indigo-700 hover:bg-indigo-50"><MessageSquare className="h-5 w-5" /> Chat with Virtual Panos</button></div></section>
    </div>
  </main><footer className="border-t border-slate-800 px-5 py-10 text-center text-sm text-slate-500">© {new Date().getFullYear()} {PERSONAL_INFO.name}. Built with React and an AI-powered portfolio assistant.</footer>
  {!isChatOpen && <button onClick={() => setIsChatOpen(true)} className="fixed bottom-6 right-6 z-40 rounded-full bg-indigo-500 p-4 text-white shadow-2xl shadow-indigo-500/30 transition-transform hover:scale-105" aria-label="Open Virtual Panos chat"><Bot className="h-6 w-6" /></button>}<ChatInterface isOpen={isChatOpen} onClose={() => setIsChatOpen(false)} isMobile={isMobile} /></div>;
}

const PortfolioApp: React.FC = () => window.location.pathname.replace(/\/+$/, '') === '/academic-projects' ? <AcademicProjectsPage /> : <PortfolioPage />;
export default PortfolioApp;
